[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "PyFinFlow"
requires-python = ">=3.8"
description = ""
authors = [
  {name = "Jakub Buczkowski"},
]